# Generated by Django 5.0.1 on 2024-03-29 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post_media', models.FileField(blank=True, null=True, upload_to='files/post/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricNumber', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('SOS', 'School of Science'), ('SOC', 'School of Computing'), ('SEET', 'School of Engineering and Engineering Technology'), ('SAAT', 'School of Agriculture and Agriculture Technology'), ('SLIT', 'School of Logistics and Innovative Technology'), ('SHHT', 'School of Health  and Health Technology'), ('SEMS', 'School of Earth and Mineral Sciences'), ('SET', 'School of Environmental Technology')], max_length=100)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='files/profiles/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
