# Generated by Django 5.0.2 on 2024-03-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, default='static/media/videos/Numbbug.mp4', null=True, upload_to='static/media/videos/'),
        ),
    ]
