# Generated by Django 5.0.1 on 2024-04-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='post_media',
        ),
        migrations.AddField(
            model_name='posts',
            name='docm',
            field=models.FileField(blank=True, null=True, upload_to='files/post/doc'),
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='files/post/image'),
        ),
    ]
