# Generated by Django 5.0.2 on 2024-03-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_posts_usertag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/media/images/'),
        ),
    ]
