# Generated by Django 5.0.2 on 2024-03-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricNumber', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('Science', 'School of Science'), ('Computing', 'School of Computing'), ('Engineering', 'School of Engineering'), ('Agriculture', 'School of Agriculture'), ('Management', 'School of Management Technology'), ('Health', 'School of Health'), ('Earth', 'School of Earth and Mineral Sciences'), ('Postgraduate', 'School of Postgraduate Studies'), ('Predegree', 'School of Predegree Studies'), ('Environmental', 'School of Environmental Technology')], max_length=100)),
                ('profile_picture', models.ImageField(default='default.jpg', upload_to='static/User/image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='posts',
            name='authordp',
        ),
    ]
