# Generated by Django 5.0.2 on 2024-03-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profiles/'),
        ),
    ]
